#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Analytics and reporting routes"""

from flask import Blueprint, request, jsonify
from flask_jwt_extended import jwt_required, get_jwt_identity
from app import db
from models import (
    ServiceRequest, ServiceLog, Invoice, Payment,
    Technician, Customer, User
)
from datetime import datetime, timedelta
from sqlalchemy import func

analytics_bp = Blueprint('analytics', __name__)


@analytics_bp.route('/dashboard', methods=['GET'])
@jwt_required()
def get_dashboard():
    """Get dashboard metrics"""
    now = datetime.utcnow()
    thirty_days_ago = now - timedelta(days=30)

    # Service request metrics
    total_requests = ServiceRequest.query.count()
    open_requests = ServiceRequest.query.filter_by(status='open').count()
    completed_requests = ServiceRequest.query.filter_by(status='completed').count()
    in_progress = ServiceRequest.query.filter_by(status='in_progress').count()

    # Revenue metrics
    paid_invoices = Invoice.query.filter_by(status='paid').all()
    total_revenue = sum(inv.total_amount for inv in paid_invoices)
    pending_revenue = sum(inv.total_amount for inv in Invoice.query.filter(
        Invoice.status.in_(['sent', 'overdue'])
    ).all())

    # Recent requests
    recent_requests = ServiceRequest.query.order_by(
        ServiceRequest.created_at.desc()
    ).limit(5).all()

    # Technician utilization
    active_technicians = Technician.query.filter_by(status='available').count()
    busy_technicians = Technician.query.filter_by(status='busy').count()

    return jsonify({
        'service_requests': {
            'total': total_requests,
            'open': open_requests,
            'in_progress': in_progress,
            'completed': completed_requests,
            'completion_rate': (completed_requests / total_requests * 100) if total_requests > 0 else 0
        },
        'revenue': {
            'total_received': total_revenue,
            'pending': pending_revenue,
            'total_potential': total_revenue + pending_revenue
        },
        'technicians': {
            'active': active_technicians,
            'busy': busy_technicians,
            'utilization_rate': (busy_technicians / (active_technicians + busy_technicians) * 100) if (active_technicians + busy_technicians) > 0 else 0
        },
        'recent_requests': [r.to_dict() for r in recent_requests]
    }), 200


@analytics_bp.route('/performance/technicians', methods=['GET'])
@jwt_required()
def technician_performance():
    """Get technician performance metrics"""
    technicians = Technician.query.all()

    performance = []
    for tech in technicians:
        total_assigned = len(tech.assignments)
        completed = len([r for r in tech.assignments if r.status == 'completed'])
        total_hours = sum(log.duration_hours for log in tech.service_logs if log.duration_hours)

        performance.append({
            'technician_id': tech.id,
            'name': tech.user.full_name,
            'specialization': tech.specialization,
            'rating': tech.rating,
            'total_assigned': total_assigned,
            'completed': completed,
            'completion_rate': (completed / total_assigned * 100) if total_assigned > 0 else 0,
            'total_hours': total_hours,
            'status': tech.status
        })

    return jsonify(performance), 200


@analytics_bp.route('/performance/customers', methods=['GET'])
@jwt_required()
def customer_performance():
    """Get customer engagement metrics"""
    customers = Customer.query.all()

    performance = []
    for customer in customers:
        total_requests = len(customer.service_requests)
        completed = len([r for r in customer.service_requests if r.status == 'completed'])
        total_spent = sum(inv.total_amount for inv in customer.invoices)

        performance.append({
            'customer_id': customer.id,
            'company_name': customer.company_name,
            'total_requests': total_requests,
            'completed': completed,
            'total_spent': total_spent,
            'status': customer.status
        })

    return jsonify(performance), 200


@analytics_bp.route('/revenue/by-technician', methods=['GET'])
@jwt_required()
def revenue_by_technician():
    """Get revenue generated by each technician"""
    technicians = Technician.query.all()

    revenue_data = []
    for tech in technicians:
        total_labor_cost = sum(
            log.labor_cost for log in tech.service_logs if log.labor_cost
        )
        revenue_data.append({
            'technician_id': tech.id,
            'name': tech.user.full_name,
            'total_labor_cost': total_labor_cost,
            'avg_hourly_rate': tech.hourly_rate
        })

    return jsonify(revenue_data), 200


@analytics_bp.route('/revenue/by-customer', methods=['GET'])
@jwt_required()
def revenue_by_customer():
    """Get revenue by customer"""
    customers = Customer.query.all()

    revenue_data = []
    for customer in customers:
        total_spent = sum(inv.total_amount for inv in customer.invoices)
        revenue_data.append({
            'customer_id': customer.id,
            'company_name': customer.company_name,
            'total_spent': total_spent,
            'invoice_count': len(customer.invoices)
        })

    return jsonify(revenue_data), 200


@analytics_bp.route('/requests/by-priority', methods=['GET'])
@jwt_required()
def requests_by_priority():
    """Get service requests breakdown by priority"""
    priorities = ['low', 'medium', 'high', 'urgent']

    data = []
    for priority in priorities:
        count = ServiceRequest.query.filter_by(priority=priority).count()
        data.append({
            'priority': priority,
            'count': count
        })

    return jsonify(data), 200


@analytics_bp.route('/requests/by-status', methods=['GET'])
@jwt_required()
def requests_by_status():
    """Get service requests breakdown by status"""
    statuses = ['open', 'assigned', 'in_progress', 'completed', 'cancelled']

    data = []
    for status in statuses:
        count = ServiceRequest.query.filter_by(status=status).count()
        data.append({
            'status': status,
            'count': count
        })

    return jsonify(data), 200


@analytics_bp.route('/requests/sla-compliance', methods=['GET'])
@jwt_required()
def sla_compliance():
    """Get SLA compliance metrics"""
    now = datetime.utcnow()

    completed_on_time = ServiceRequest.query.filter(
        ServiceRequest.status == 'completed',
        ServiceRequest.actual_end_time <= ServiceRequest.sla_end_time
    ).count()

    total_with_sla = ServiceRequest.query.filter(
        ServiceRequest.sla_end_time != None
    ).count()

    compliance_rate = (completed_on_time / total_with_sla * 100) if total_with_sla > 0 else 0

    return jsonify({
        'total_with_sla': total_with_sla,
        'completed_on_time': completed_on_time,
        'compliance_rate': round(compliance_rate, 2)
    }), 200


@analytics_bp.route('/reports/monthly', methods=['GET'])
@jwt_required()
def monthly_report():
    """Get monthly performance report"""
    month = request.args.get('month', default=datetime.utcnow().month, type=int)
    year = request.args.get('year', default=datetime.utcnow().year, type=int)

    start_date = datetime(year, month, 1)
    if month == 12:
        end_date = datetime(year + 1, 1, 1)
    else:
        end_date = datetime(year, month + 1, 1)

    # Service metrics
    requests_created = ServiceRequest.query.filter(
        ServiceRequest.created_at.between(start_date, end_date)
    ).count()

    requests_completed = ServiceRequest.query.filter(
        ServiceRequest.status == 'completed',
        ServiceRequest.actual_end_time.between(start_date, end_date)
    ).count()

    # Revenue metrics
    invoices = Invoice.query.filter(
        Invoice.issue_date.between(start_date, end_date),
        Invoice.status == 'paid'
    ).all()

    total_revenue = sum(inv.total_amount for inv in invoices)

    # Labor metrics
    service_logs = ServiceLog.query.filter(
        ServiceLog.start_time.between(start_date, end_date)
    ).all()

    total_hours = sum(log.duration_hours for log in service_logs if log.duration_hours)
    total_labor_cost = sum(log.labor_cost for log in service_logs if log.labor_cost)

    return jsonify({
        'period': f'{year}-{month:02d}',
        'requests': {
            'created': requests_created,
            'completed': requests_completed,
            'completion_rate': (requests_completed / requests_created * 100) if requests_created > 0 else 0
        },
        'revenue': {
            'total': total_revenue,
            'invoice_count': len(invoices)
        },
        'labor': {
            'total_hours': total_hours,
            'total_cost': total_labor_cost
        }
    }), 200


@analytics_bp.route('/health-check', methods=['GET'])
@jwt_required()
def system_health():
    """Get system health indicators"""
    now = datetime.utcnow()

    # Overdue requests
    overdue = ServiceRequest.query.filter(
        ServiceRequest.sla_end_time < now,
        ServiceRequest.status != 'completed'
    ).count()

    # Overdue invoices
    overdue_invoices = Invoice.query.filter(
        Invoice.due_date < now,
        Invoice.status != 'paid'
    ).count()

    # Low stock items
    from models import Inventory
    low_stock = Inventory.query.filter(
        Inventory.quantity < Inventory.min_quantity
    ).count()

    return jsonify({
        'overdue_requests': overdue,
        'overdue_invoices': overdue_invoices,
        'low_stock_items': low_stock,
        'system_status': 'healthy' if overdue < 10 and overdue_invoices < 5 else 'warning'
    }), 200
